name = "workers-ai2api"
main = "_worker.js"
compatibility_date = "2026-06-30"

[[kv_namespaces]]
binding = "KV"
id = "2422102dccd7458eb57546e36e7cebc9"

[vars]
# ADMIN_PASSWORD = "120322lsh"
# CUSTOM_MODEL_MAP = "{}"
